### ISSUE TITLE
Optional structs with an Option value always deserialize to None

### ISSUE THREAD

**Issue by Tony-Samuels** [Xuanwo/serde-env#24]
Example code:

```rust
#![allow(dead_code)]

#[derive(Debug, serde::Deserialize)]
struct Inner {
    val: Option<u32>,
}

#[derive(Debug, serde::Deserialize)]
struct Outer {
    inner: Inner,
}

#[derive(Debug, serde::Deserialize)]
struct OuterOpt {
    inner: Option<Inner>,
}

fn main() {
    println!("{:?}", serde_env::from_env::<Outer>());
    println!("{:?}", serde_env::from_env::<OuterOpt>());
}
```

Example output:
```console
$ INNER_VAL=3 cargo run -q
Ok(Outer { inner: Inner { val: Some(3) } })
Ok(OuterOpt { inner: None })
```

As both have the same form and accept the same values, the two `Inner` should have the same value.

**Comment by Tony-Samuels** [comment]
I think the issue is that `deserialize_option` only checks if `self.0.value()` is empty, whereas `Node` should probably have its own `is_empty` function that is just `self.0.is_empty() && self.1.is_empty()`.

This seems to work, but I haven't checked any complicated cases yet, just verified it doesn't break the tests and solves the above example. 

If I get some time, I'll test it more thoroughly and raise an MR.

**Comment by Tony-Samuels** [comment]
Is there any plan to make a new release soon?

**Comment by Xuanwo** [comment]
> Is there any plan to make a new release soon?

Ok, I will make a release now.
